[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "northarray", email = "271184997+northarray@users.noreply.github.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "bokeh",
    "fastcore",
    "holoviews",
    "hvplot",
    "matplotlib",
    "numpy",
    "pandas",
    "panel",
    "scipy",
]

[project.urls]
Repository = "https://github.com/northarray/portfolio"
Documentation = "https://northarray.github.io/portfolio/"

[project.entry-points.nbdev]
portfolio = "portfolio._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "portfolio.__version__"}

[tool.setuptools.packages.find]
include = ["portfolio"]

[tool.nbdev]
