"""Docs: https://northarray.github.io/portfolio/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = ['Portfolio', 'compare']

# %% ../nbs/core.ipynb #106f62e7
from collections import defaultdict

# %% ../nbs/core.ipynb #c6b1ed6b
import numpy as np

# %% ../nbs/core.ipynb #be596cc5
from fastcore.basics import *

# %% ../nbs/core.ipynb #b4423a4a
import pandas as pd

# %% ../nbs/core.ipynb #e1ad1fbe
def _slice_dates(data, start, end):
    if not start: start = data.index.min()
    if not end: end = data.index.max()
    return data.loc[start:end]

# %% ../nbs/core.ipynb #be66f3dc
def _validate(name, df):
    if df is not None:
        is_monthly = isinstance(df.index, pd.PeriodIndex) and df.index.freqstr == 'M'
        if not is_monthly: raise ValueError(f'{name} df has an index that is not a period index with monthly frequency. Resample your data to monthly frequency')

# %% ../nbs/core.ipynb #a9d0aa43
class Portfolio:
    def __init__(self, name:str, return_streams:pd.DataFrame, weights:dict, rf:pd.DataFrame=None, cpi:pd.DataFrame=None, funding_spread:float=0.0, start=None, end=None):
        for n,df in zip(('return_streams', 'rf', 'cpi'),(return_streams, rf, cpi)): _validate(n,df)

        self.name = name
        self.weights = weights
        self.funding_spread = funding_spread
        self.full_rf = rf.copy() if rf is not None else None
        self.full_cpi = cpi.copy() if cpi is not None else None
        self.full_rets = return_streams[list(weights.keys())].copy()

        self.return_streams = _slice_dates(self.full_rets, start, end)
        self.rf = self.full_rf.reindex(self.return_streams.index) if self.full_rf is not None else None
        self.cpi = self.full_cpi.reindex(self.return_streams.index) if self.full_cpi is not None else None
    def __repr__(self): return str(self.weights)

# %% ../nbs/core.ipynb #35f353eb
def _availability_row(df):
    valid = df.dropna().index
    expected = pd.period_range(valid.min(), valid.max(), freq="M")
    return {
        "start": valid.min(),
        "end": valid.max(),
        "observations": len(valid),
        "missing_months": len(expected.difference(valid)),
    }

# %% ../nbs/core.ipynb #72a21ff3
@patch(as_prop=True)
def availability(self: Portfolio):
    "Information on the underlying data powering the analysis"
    rows = {"returns": _availability_row(self.full_rets)}
    if self.full_rf is not None: rows["rf"] = _availability_row(self.full_rf)
    if self.full_cpi is not None:rows["cpi"] = _availability_row(self.full_cpi)
    return pd.DataFrame.from_dict(rows, orient="index")

# %% ../nbs/core.ipynb #bf597183
@patch
def between(self:Portfolio, start=None, end=None):
    "Changes performance time period from start to end"
    return Portfolio(self.name, self.full_rets, self.weights, rf=self.full_rf, cpi=self.full_cpi, funding_spread=self.funding_spread, start=start, end=end)


# %% ../nbs/core.ipynb #f042c26d
@patch()
def _excess_return(self:Portfolio):
    if self.rf is None: raise ValueError("Cannot calculate excess returns: no risk-free rate was supplied.")
    return self.return_streams.sub(self.rf, axis=0)

# %% ../nbs/core.ipynb #b569ef55
@patch()
def port_rets(self:Portfolio, excess=True, agg=True):
    'Monthly portfolio return'
    stream = self._excess_return() if excess else self.return_streams
    r = (stream*self.weights)
    if agg: r = r.sum(axis=1, min_count=len(self.weights))
    r.name = self.name
    return r

# %% ../nbs/core.ipynb #cf19357f
def _sharpe(rets: pd.DataFrame):
    'Calculates annualised excess return, volatility and sharpe'
    exp_r = rets.mean() * 12
    vol = rets.std() * 12**0.5
    sharpe = exp_r/vol
    return exp_r,vol,sharpe

# %% ../nbs/core.ipynb #e57ff917
@patch
def stats(self:Portfolio):
    'Excess return, volatility and sharpe ratio (annualised)'
    e,v,s = _sharpe(self.port_rets())
    stats = {'expected_return': e, 'volatility': v, 'sharpe_ratio': s}
    return pd.Series(stats, name=self.name)

# %% ../nbs/core.ipynb #eee154fc
@patch
def cum_return(self:Portfolio):
    'Cumulative compounded total return'
    r = self.port_rets(excess=False)
    return (1+r).cumprod()

# %% ../nbs/core.ipynb #a69502ff
@patch
def real_r(self: Portfolio, components=False):
    'Real (inflation-adjusted) return'
    if self.cpi is None:
        raise ValueError("You must specify CPI data to compute real returns")
    r = self.port_rets(excess=False)
    if components: r = self.return_streams.join(r)
    real_r = (1+r).div(1+self.cpi, axis=0)-1
    return real_r.dropna()

# %% ../nbs/core.ipynb #753ea704
@patch
def real_w(self:Portfolio):
    'Real total wealth, your total compounded wealth less inflation'
    r = self.real_r()
    real_w = (1+r).cumprod()
    real_w.name = self.name
    return real_w

# %% ../nbs/core.ipynb #64846c02
@patch
def roll_return(self:Portfolio, months=12, excess=True, extras=False, forward=False):
    'Rolling return (linearly summed) expressed in annualised terms.'
    years = months/12
    r = self.port_rets(excess=excess)
    if extras: r = r.to_frame().join(self.rf).join(self.cpi).dropna()
    if forward: r = r[::-1]
    r = r.rolling(months).sum().dropna()
    if forward: r = r[::-1]
    return r/years

# %% ../nbs/core.ipynb #9c86797b
@patch
def cum_excess_return(self:Portfolio):
    "Cumulative sum of monthly returns (no compounding)"
    return self.port_rets().cumsum()

# %% ../nbs/core.ipynb #770404d6
@patch
def detrended_cum_return(self:Portfolio):
    "Cumulative sum of returns minus long-run mean"
    r = self.port_rets()
    return (r - r.mean()).cumsum()

# %% ../nbs/core.ipynb #e8909b6c
def _align_portfolios(*portfolios):
    "Return new portfolios restricted to their common valid dates."
    ix = portfolios[0].return_streams.index
    for p in portfolios[1:]: ix = ix.intersection(p.return_streams.index)
    return (p.between(ix.min(), ix.max()) for p in portfolios)

# %% ../nbs/core.ipynb #a32cb8c7
def compare(*portfolios, metric='stats', **kwargs):
    'Compares two portfolios using a metric'
    portfolios = _align_portfolios(*portfolios)
    df = pd.concat([getattr(p, metric)(**kwargs) for p in portfolios], axis=1)
    df.name = metric
    return df

# %% ../nbs/core.ipynb #a443141c
@patch
def asset_stats(self:Portfolio):
    'Expected excess return, volatility and sharpe ratio'
    e,v,s = _sharpe(self.port_rets(agg=False))
    stats = {'expected_return': e, 'volatility': v, 'sharpe_ratio': s}
    return pd.DataFrame(stats).T

# %% ../nbs/core.ipynb #4303b0e9
@patch
def risk_contribution(self:Portfolio):
    "Per-asset risk contribution as percentage of portfolio variance"
    cov = self.port_rets(agg=False).join(self.port_rets()).cov() * 12
    pv = cov.loc[self.name, self.name]
    rc = {a: cov.loc[a, self.name] / pv for a in self.weights}
    return pd.Series(rc, name=self.name)

# %% ../nbs/core.ipynb #aef8fd2c
@patch
def correlation(self:Portfolio):
    "Pairwise correlation matrix of underlying assets and portfolio"
    return self.port_rets(agg=False).join(self.port_rets()).corr()

# %% ../nbs/core.ipynb #5c496be2
@patch
def return_drivers(self:Portfolio, months=12*5):
    "Asset and portfolio rolling return"
    return self.port_rets(agg=False).join(self.port_rets()).rolling(months).agg(sum).dropna()

# %% ../nbs/core.ipynb #9caadac6
@patch
def drawdown_series(self:Portfolio, assets=False):
    "Drawdown series"
    wealth = self.cum_return()
    if assets: wealth = (1+self._port_rets(excess=False, agg=False)).cumprod().join(wealth)
    return wealth / wealth.cummax() - 1

# %% ../nbs/core.ipynb #381b825e
@patch
def max_drawdown(self:Portfolio):
    "Worst peak-to-trough decline"
    return self.drawdown_series().min().item()

# %% ../nbs/core.ipynb #40aa7aaa
@patch
def r_by_decade(self: Portfolio):
    "Real return grouped by decade"
    decade_starts = [y for y in range(1900, 2030, 10)]
    blocks = [self.real_r().loc[f'{y}-01-01':f'{y+9}-12-31'] for y in decade_starts]
    blocks = [b for b in blocks if len(b) == 120]
    df = [pd.concat([pd.Series([1]), 1+b]).cumprod().reset_index(drop=True) for b in blocks]
    df = pd.concat(df, axis=1)
    df.columns = [f'{b.index[0].year}s' for b in blocks]
    df.index = df.index/12 # normalize months to years
    return df

# %% ../nbs/core.ipynb #c3d1b055
@patch
def rolling_vol(self:Portfolio, months=24):
    "Annualised rolling volatility per asset"
    return self.port_rets(excess=False, agg=False).rolling(months).agg(lambda x: x.std() * 12**0.5).dropna()

# %% ../nbs/core.ipynb #bfdf4d1f
@patch
def rc_simple(self:Portfolio):
    'Simple risk contribution metric'
    vol = self.rolling_vol()
    tot = vol.sum(axis=1)
    rc = vol.div(tot, axis=0)
    return rc
