# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/eod_download.ipynb.

# %% auto #0
__all__ = ['EOD_DIR']

# %% ../nbs/eod_download.ipynb #b421aa09
from pathlib import Path

# %% ../nbs/eod_download.ipynb #eb084a4b
EOD_DIR = Path.home()/'.cache'/'eod_data'
EOD_DIR.mkdir(parents=True, exist_ok=True)

# %% ../nbs/eod_download.ipynb #ed7a7212
from .util import data_path
