# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ledger.ipynb.

# %% auto #0
__all__ = ['Ledger']

# %% ../nbs/ledger.ipynb #59f38d92
from pathlib import Path

# %% ../nbs/ledger.ipynb #a8db2c74
import numpy as np
from fastcore.all import patch, store_attr
from scipy.optimize import brentq
import pandas as pd

# %% ../nbs/ledger.ipynb #e63c613e
from fastcore.all import patch

# %% ../nbs/ledger.ipynb #6f935014
class Ledger:
    "Live portfolio ledger: raw transactions + prices in a common currency"
    def __init__(self, txns, prices, eod_dir=None):
        store_attr()
        wide = txns.pivot_table(index='date', columns='symbol', values=['units', 'tot_invested'], aggfunc='sum')
        self.units_held  = wide['units'].cumsum().reindex(prices.index).ffill()
        self.money_spent = wide['tot_invested'].cumsum().reindex(prices.index).ffill()
        self.market_value = self.units_held * prices
        self.p_l = (self.market_value - self.money_spent).dropna(how='all')
    def __repr__(self): return f"Ledger({list(self.prices.columns)}, {self.prices.index[0].date()} to {self.prices.index[-1].date()})"

# %% ../nbs/ledger.ipynb #001a0967
@patch(as_prop=True)
def symbols(self:Ledger): return list(self.prices.columns)

# %% ../nbs/ledger.ipynb #cd379e90
@patch
def as_of(self:Ledger, date=None):
    "Total P&L per asset at `date` (default: latest)"
    return self.p_l.asof(date or self.p_l.index[-1])

# %% ../nbs/ledger.ipynb #a0705922
@patch(as_prop=True)
def allocation(self:Ledger):
    "Daily allocation weights (fraction of total market value per asset)"
    return self.market_value.div(self.market_value.sum(axis=1), axis=0).dropna(how='all').round(3)

# %% ../nbs/ledger.ipynb #15227641
def _npv(r, flows):
    yrs = (flows.index - flows.index[0]).days / 365
    return (flows.values / (1+r)**yrs.values).sum()

# %% ../nbs/ledger.ipynb #8ad3a80b
@patch
def irr(self:Ledger):
    "Annualised money-weighted return (IRR) for the whole portfolio"
    flows = self.txns.groupby('date')['tot_invested'].sum().mul(-1)
    today = self.prices.index[-1]
    flows[today] = flows.get(today, 0) + float(self.market_value.loc[today].sum())
    flows = flows.sort_index()
    return brentq(_npv, -0.9, 10, args=(flows,))

# %% ../nbs/ledger.ipynb #3ab7ac95
@patch
def twrr(self:Ledger):
    "Monthly asset returns and lagged weights for use with Portfolio"
    asset_rets = self.prices.resample('MS').last().pct_change()
    weights = self.allocation.resample('MS').last().shift().where(lambda w: w != 0)
    return asset_rets, weights

# %% ../nbs/ledger.ipynb #da7cec87
def _parse_txns(path):
    "Parse brokerage CSV, fix dtypes and sign-encode units"
    txns = pd.read_csv(path)
    txns['Kurs'] = txns['Kurs'].str.replace(',', '.').astype(float)
    txns['Affärsdag'] = pd.to_datetime(txns.Affärsdag)
    txns['Antal'] = txns.Antal.where(txns.Transaktionstyp=='KÖPT', txns.Antal*-1)
    return txns

# %% ../nbs/ledger.ipynb #e8c090a4
def _load_prices(eod_dir, assets):
    "Load and forward-fill EOD price CSVs for `assets`"
    dfs = [pd.read_csv(Path(eod_dir)/f'{a}.csv', index_col=0, parse_dates=True)[['adjusted_close']].rename(columns=lambda _: a) for a in assets]
    return pd.concat(dfs, axis=1, sort=True)

# %% ../nbs/ledger.ipynb #0e793f53
def _get_currency(assets, eod_dir):
    return {k: v for a in assets for k, v in pd.read_csv(Path(eod_dir)/f'{a}.csv').set_index('ISIN')['Currency'].to_dict().items()}

# %% ../nbs/ledger.ipynb #530bd11c
def _to_sek(txns, prices, fx:pd.Series, eod_dir):
    "Convert EUR-denominated transactions and prices to SEK"
    txns = txns.copy()
    prices = prices.copy()

    # convert txns
    mask = (txns['Valuta'] == 'EUR').values
    txns.loc[mask, 'Kurs'] *= fx.reindex(txns['Affärsdag'], method='ffill')[mask].values
    txns.loc[mask, 'Valuta'] = 'SEK'

    # convert market prices
    eur_traded = [k for k,v in _get_currency(prices.columns, eod_dir).items() if v=='EUR']
    prices.loc[:, eur_traded] = prices.loc[:, eur_traded].multiply(fx.reindex(prices.index, method='ffill'), axis=0)

    return txns, prices

# %% ../nbs/ledger.ipynb #7d56869f
def _clean_txns(txns):
    "Rename and add tot_invested column"
    tx = txns[['Affärsdag','ISIN','Antal','Kurs']].copy()
    tx.columns = ['date','symbol','units','price']
    tx['tot_invested'] = tx.units * tx.price
    return tx

# %% ../nbs/ledger.ipynb #047b8848
@patch(cls_method=True)
def from_csv(cls:Ledger, txns_path, eod_dir, drop=None, fx='EURSEK'):
    "Build a Ledger from a brokerage transactions CSV and EOD price directory"
    txns = _parse_txns(txns_path)
    prices = _load_prices(eod_dir, list(txns.ISIN.unique()))
    fx_df = _load_prices(eod_dir, [fx])

    txns, prices = _to_sek(txns, prices, fx_df[fx], eod_dir)
    drop = (drop or [])
    prices = prices.drop(columns=drop).ffill()
    txns = _clean_txns(txns[~txns.ISIN.isin(drop)])
    return cls(txns, prices, eod_dir)

# %% ../nbs/ledger.ipynb #5e983f4b
@patch
def get_names(self:Ledger):
    if self.eod_dir:
        assets = self.prices.columns
        return {k: v for a in assets for k, v in pd.read_csv(Path(self.eod_dir)/f'{a}.csv').set_index('ISIN')['Name'].to_dict().items()}
