"""Docs: https://northarray.github.io/portfolioportfolio.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/portfolio.ipynb.

# %% auto #0
__all__ = ['Portfolio', 'sharpe', 'compare']

# %% ../nbs/portfolio.ipynb #106f62e7
from collections import defaultdict

# %% ../nbs/portfolio.ipynb #c6b1ed6b
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt
import numpy as np

# %% ../nbs/portfolio.ipynb #be596cc5
from fastcore.basics import *

# %% ../nbs/portfolio.ipynb #b4423a4a
import pandas as pd

# %% ../nbs/portfolio.ipynb #e1ad1fbe
def _slice_dates(data, start, end):
    if not start: start = data.index.min()
    if not end: end = data.index.max()
    return data.loc[start:end]

# %% ../nbs/portfolio.ipynb #a9d0aa43
class Portfolio:
    def __init__(self, name:str, return_streams:pd.DataFrame, weights:dict, rf:pd.DataFrame=None, cpi:pd.DataFrame=None, funding_spread:float=0.0, start=None, end=None):
        self.name = name
        self.weights = weights
        self.funding_spread = funding_spread
        assets = list(weights.keys())
        self.full_rf = rf.copy() if rf is not None else None
        self.full_cpi = cpi.copy() if cpi is not None else None
        self.full_rets = return_streams[assets].copy()
        self.rf = _slice_dates(self.full_rf, start, end) if self.full_rf is not None else None
        self.cpi = _slice_dates(self.full_cpi, start, end) if self.full_cpi is not None else None
        self.raw_rets = _slice_dates(self.full_rets, start, end)
        self.return_streams = self.raw_rets.sub(self.rf, axis=0) if self.rf is not None else self.raw_rets.copy()
    def __repr__(self): return str(self.weights)

# %% ../nbs/portfolio.ipynb #bf597183
@patch
def between(self:Portfolio, start=None, end=None):
    "New `Portfolio` sliced to `start`/`end` from the full (never-sliced) history"
    return Portfolio(self.name, self.full_rets, self.weights, rf=self.full_rf, cpi=self.full_cpi, funding_spread=self.funding_spread, start=start, end=end)


# %% ../nbs/portfolio.ipynb #b569ef55
@patch()
def _port_rets(self:Portfolio, excess=True, agg=True):
    stream = self.return_streams if excess else self.raw_rets
    r = (stream*self.weights)
    if agg: r = r.sum(axis=1)
    r.name = self.name
    return r

# %% ../nbs/portfolio.ipynb #e48c1e8d
@patch(as_prop=True)
def port_rets(self:Portfolio):
    return self._port_rets()

# %% ../nbs/portfolio.ipynb #cf19357f
def sharpe(rets: pd.DataFrame):
    'Calculates annualized exp-excess return, vol and sharpe, assumes monthly returns data'
    exp_r = rets.mean() * 12
    vol = rets.std() * 12**0.5
    sharpe = exp_r/vol
    return exp_r,vol,sharpe

# %% ../nbs/portfolio.ipynb #e57ff917
@patch
def stats(self:Portfolio):
    'Basic portfolio (annualised) stats: exp-excess return, vol and sharpe ratio'
    e,v,s = sharpe(self.port_rets)
    stats = {'expected_return': e, 'volatility': v, 'sharpe_ratio': s}
    return pd.Series(stats, name=self.name)

# %% ../nbs/portfolio.ipynb #eee154fc
@patch
def cum_return(self:Portfolio):
    'Cumulative compounded total return'
    r = self._port_rets(excess=False)
    return (1+r).cumprod()

# %% ../nbs/portfolio.ipynb #a69502ff
@patch
def real_r(self: Portfolio, components=False):
    if self.cpi is None:
        raise ValueError("You must specify CPI data to compute real returns")
    r = self._port_rets(excess=False)
    if components: r = self.raw_rets.join(r)
    real_r = (1+r).div(1+self.cpi, axis=0)-1
    return real_r.dropna()

# %% ../nbs/portfolio.ipynb #753ea704
@patch
def real_w(self:Portfolio):
    'Total real wealth'
    r = self.real_r()
    real_w = (1+r).cumprod()
    real_w.name = self.name
    return real_w

# %% ../nbs/portfolio.ipynb #64846c02
@patch
def roll_return(self:Portfolio, months=12, excess=True, extras=False, forward=False):
    'Rolling (excess) return (linearly summed) expressed in annualised terms.'
    years = months/12
    r = self._port_rets(excess=excess)
    if extras: r = r.to_frame().join(self.rf).join(self.cpi).dropna()
    if forward: r = r[::-1]
    r = r.rolling(months).sum().dropna()
    if forward: r = r[::-1]
    return r/years

# %% ../nbs/portfolio.ipynb #9c86797b
@patch
def cum_excess_return(self:Portfolio):
    "Cumulative sum of monthly returns (no compounding)"
    return self.port_rets.cumsum()

# %% ../nbs/portfolio.ipynb #770404d6
@patch
def detrended_cum_return(self:Portfolio):
    "Cumulative sum of returns minus long-run mean — removes drift, shows environmental cycles"
    r = self.port_rets
    return (r - r.mean()).cumsum()

# %% ../nbs/portfolio.ipynb #a32cb8c7
def compare(*portfolios, metric='stats', **kwargs):
    df = pd.concat([getattr(p, metric)(**kwargs) for p in portfolios], axis=1)
    df.name = metric
    return df

# %% ../nbs/portfolio.ipynb #18850215
@patch(as_prop=True)
def asset_rets(self:Portfolio):
    return (self.return_streams*self.weights)[self.weights.keys()]

# %% ../nbs/portfolio.ipynb #a443141c
@patch
def asset_stats(self:Portfolio):
    'Basic portfolio (annualised) stats: exp return, vol and sharpe ratio'
    e,v,s = sharpe(self.asset_rets)
    stats = {'expected_return': e, 'volatility': v, 'sharpe_ratio': s}
    return pd.DataFrame(stats).T

# %% ../nbs/portfolio.ipynb #4303b0e9
@patch
def risk_contribution(self:Portfolio):
    "Per-asset risk contribution as % of portfolio variance (sums to 1)"
    cov = self.asset_rets.join(self.port_rets).cov() * 12
    pv = cov.loc[self.name, self.name]
    rc = {a: cov.loc[a, self.name] / pv for a in self.weights}
    return pd.Series(rc, name=self.name)

# %% ../nbs/portfolio.ipynb #aef8fd2c
@patch
def correlation(self:Portfolio):
    "Pairwise correlation matrix of underlying assets and portfolio"
    return self.asset_rets.join(self.port_rets).corr()

# %% ../nbs/portfolio.ipynb #5c496be2
@patch
def return_drivers(self:Portfolio, months=12*5):
    "Calculates portfolio and asset rolling return mean centered"
    return self.asset_rets.join(self.port_rets).rolling(months).agg(sum).dropna()

# %% ../nbs/portfolio.ipynb #9caadac6
@patch
def drawdown_series(self:Portfolio, assets=False):
    "Time series of drawdowns from rolling peak"
    wealth = self.cum_return()
    if assets: wealth = (1+self._port_rets(excess=False, agg=False)).cumprod().join(wealth)
    return wealth / wealth.cummax() - 1

# %% ../nbs/portfolio.ipynb #381b825e
@patch
def max_drawdown(self:Portfolio):
    "Worst peak-to-trough decline over full history"
    return self.drawdown_series().min().item()

# %% ../nbs/portfolio.ipynb #8364b8de
@patch
def lost_decade(self: Portfolio, components=False, months=120):
    "Real forward 10y returns (ann)"
    real_r = self.real_r(components=components)
    annual = (1 + real_r)[::-1].rolling(months).agg(np.prod)[::-1] ** (1/10) - 1
    return annual.dropna()

# %% ../nbs/portfolio.ipynb #40aa7aaa
@patch
def r_by_decade(self: Portfolio):
    "Real return series per decade"
    decade_starts = [y for y in range(1900, 2030, 10)]
    blocks = [self.real_r().loc[f'{y}-01-01':f'{y+9}-12-31'] for y in decade_starts]
    blocks = [b for b in blocks if len(b) == 120]
    df = [pd.concat([pd.Series([1]), 1+b]).cumprod().reset_index(drop=True) for b in blocks]
    df = pd.concat(df, axis=1)
    df.columns = [f'{b.index[0].year}s' for b in blocks]
    df.index = df.index/12 # normalize months to years
    return df

# %% ../nbs/portfolio.ipynb #c3d1b055
@patch
def rolling_vol(self:Portfolio, months=24):
    "Annualised rolling vol per asset over `months` window"
    return self._port_rets(excess=False, agg=False).rolling(months).agg(lambda x: x.std() * 12**0.5).dropna()

# %% ../nbs/portfolio.ipynb #bfdf4d1f
@patch
def rc_simple(self:Portfolio):
    vol = self.rolling_vol()
    tot = vol.sum(axis=1)
    rc = vol.div(tot, axis=0)
    return rc

# %% ../nbs/portfolio.ipynb #b8325507
def _plot(data, log, title):
    m = np.log2(data) if log else data
    ax = m.plot(figsize=(12,6), title=title)
    if log:
        ymin,ymax = int(np.floor(m.min().min())), int(np.ceil(m.max().max()))
        ax.set_yticks(range(ymin, ymax+1))
        ax.yaxis.set_major_formatter(ticker.FuncFormatter(lambda y, _: f'{2.**y:.1f}x'))
    ax.grid(True, which='both', alpha=0.3)
    return ax

# %% ../nbs/portfolio.ipynb #f9342ea3
@patch
def portfolio_plot(self:pd.DataFrame, log=False):
    title = getattr(self, 'name', ', '.join(self.columns))
    return _plot(self, log, title)

# %% ../nbs/portfolio.ipynb #c522d2dc
@patch
def portfolio_plot(self:pd.Series, log=False):
    title = getattr(self, 'name', 'unknown')
    return _plot(self, log, title)
