# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sample_data.ipynb.

# %% auto #0
__all__ = ['sample_data']

# %% ../nbs/sample_data.ipynb #df527746
import pandas as pd
import numpy as np

# %% ../nbs/sample_data.ipynb #aad89bb2
def sample_data():
    idx = pd.date_range('1992-06-01', periods=120, freq='MS')
    rets = pd.DataFrame(dict(bonds=np.random.normal(0.004, 0.02, 120), stocks=np.random.normal(0.007, 0.04, 120)), index=idx)
    rets.index.name = 'date'

    rf = pd.Series(np.random.uniform(0.001, 0.004, 120), index=idx, name='rf')
    rf.index.name = 'date'

    cpi = pd.Series(np.random.uniform(0.001, 0.003, 120), index=idx, name='united_states_cpi')
    cpi.index.name = 'date'
    return rets, rf, cpi
