"""Docs: https://northarray.github.io/portfolio/sample_data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/sample_data.ipynb.

# %% auto #0
__all__ = ['sample_data', 'sample_data_se']

# %% ../nbs/sample_data.ipynb #f83a8ada
from pathlib import Path

# %% ../nbs/sample_data.ipynb #df527746
import pandas as pd
import numpy as np

# %% ../nbs/sample_data.ipynb #ea256e01
from .util import data_path

# %% ../nbs/sample_data.ipynb #aad89bb2
def sample_data():
    idx = pd.date_range('1992-06-01', periods=120, freq='MS')
    rets = pd.DataFrame(dict(bonds=np.random.normal(0.004, 0.02, 120), stocks=np.random.normal(0.007, 0.04, 120)), index=idx)
    rets.index.name = 'date'

    rf = pd.Series(np.random.uniform(0.001, 0.004, 120), index=idx, name='rf')
    rf.index.name = 'date'

    cpi = pd.Series(np.random.uniform(0.001, 0.003, 120), index=idx, name='united_states_cpi')
    cpi.index.name = 'date'
    return rets.to_period(), rf.to_period(), cpi.to_period()

# %% ../nbs/sample_data.ipynb #de79a0dd
def sample_data_se():
    p = data_path()
    rets = pd.read_csv(p/'sample_portfolio_returns.csv', index_col=0, parse_dates=True)
    rets = rets.rename(columns={'se_equities': 'stocks', 'se_bonds': 'bonds'})
    rf = pd.read_csv(p/'sample_portfolio_rf.csv', index_col=0, parse_dates=True)
    rf = rf.sweden_short_rate
    rf.name = 'rf'
    cpi = pd.read_csv(p/'sample_portfolio_cpi.csv', index_col=0, parse_dates=True)
    return rets.to_period(),rf.to_period(),cpi.cpi.to_period()
