# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/strategies.ipynb.

# %% auto #0
__all__ = ['volatility_matched']

# %% ../nbs/strategies.ipynb #e48dcf36
def volatility_matched(return_streams):
    vols = return_streams.std()
    inv_vols = 1 / vols
    return (inv_vols / inv_vols.sum()).to_dict()
