# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/util.ipynb.

# %% auto #0
__all__ = ['data_path']

# %% ../nbs/util.ipynb #f83a8ada
from pathlib import Path

# %% ../nbs/util.ipynb #72373282
def data_path():
    import portfolio
    return Path(portfolio.__file__).parent.parent/'data'
